### ISSUE TITLE
feature request: options to disable automatic commits

### ISSUE THREAD

**Issue by stevenh** [zbindenren/cc#7]
Have looked at the code it seems like this tool will try to automatically commit and create releases.

It would be nice if this was optional behaviour, which was disabled by default.

**Comment by zbindenren** [comment]
Have you tried the option -stdout? This prints the output only and performs no commits.

**Comment by stevenh** [comment]
I did spot that so I guess I could redirect that to the file.

I was wondering if adding something like the following flags  `--commit` or a `--release` might result in a more understood flow as per other tools which have similar functionality but aren't written in go like clog?

**Comment by zbindenren** [comment]
> I did spot that so I guess I could redirect that to the file.
> 
> I was wondering if adding something like the following flags `--commit` or a `--release` might result in a more understood flow as per other tools which have similar functionality but aren't written in go like clog?

This would change the current API of the CLI and I prefer not to do that.

**Comment by stevenh** [comment]
Understood, something for a v2 consideration.

In the mean time there could be a `--no-commit` `--no-release` or even a `--changelog-only`

**Comment by zbindenren** [comment]
Your feature can be done with:

```
changelog -stdout -n > /dev/null
```
